version: '3'

services:
  teamserver:
    build: teamserver/
    ports:
      - "80:80"
    sysctls:
      net.core.somaxconn: 1024

    environment:
      - MODE=DEBUG
      - CELERY_BROKER_URL=redis://arsenal_redis_1:6379/0
      - DB_NAME=arsenal
      - DB_HOST=arsenal_mongo_1
      - DB_PORT=27017
      #- DB_USER=
      - DB_PASS=password
      #- SLACK_ENABLED=True
      #- SLACK_API_TOKEN=None

  redis:
    image: redis

  mongo:
    image: mongo
